name: 每日新闻邮件
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # 加这一行就消除警告


jobs:
  send-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run & Send
        env:
          SENDER_EMAIL: ${{ secrets.MAIL_USERNAME }}
          SENDER_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.MAIL_USERNAME }}
        run: python send_email.py
